concurrency:
  cancel-in-progress: true
  group: dlc-${{ github.event.pull_request.number || github.ref }}
jobs:
  CheckDeadLinks:
    if: (github.event_name == 'schedule' && github.repository == 'apache/skywalking')
      || (github.event_name != 'schedule')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      run: sudo npm install -g markdown-link-check@3.10.0
    - continue-on-error: true
      run: "for file in $(find . -name \"*.md\"); do\n  markdown-link-check -c .dlc.json\
        \ -q \"$file\"\ndone\n"
    timeout-minutes: 30
name: Dead Link Checker
on:
  repository_dispatch:
    types: trigger-ga___dead-link-checker.yaml
