env:
  HUB: ghcr.io/apache/skywalking
  SKIP_TEST: true
jobs:
  build:
    env:
      TAG: ${{ github.sha }}
    if: github.repository == 'apache/skywalking'
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ env.HUB }}
        username: ${{ github.actor }}
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      name: Build and push images
      run: make -C test build.e2e-service docker.push-e2e-service
    timeout-minutes: 90
name: Publish E2E service images
on:
  repository_dispatch:
    types: trigger-ga___publish-docker-e2e-service.yaml
